export const mockBags = [
  {
    id: 1,
    title: "日替わり手作りおばんざいセット",
    storeName: "和食処 みやび",
    originalPrice: 1200,
    discountedPrice: 500,
    pickupStart: "18:00",
    pickupEnd: "20:00",
    distance: "350m",
    category: "meals",
    itemType: "bag",
    ownerComment: "今日は肉じゃがが多めに入っています。温めてお召し上がりください！",
    photoUrl: "/__mockup/images/refine-b/meal_1.png",
    soldOut: false,
    lowStock: true,
    rating: 4.8,
  },
  {
    id: 2,
    title: "焼き立てクロワッサン詰め合わせ",
    storeName: "ベーカリー こむぎ",
    originalPrice: 1500,
    discountedPrice: 600,
    pickupStart: "17:30",
    pickupEnd: "19:00",
    distance: "1.2km",
    category: "bakery_sweets",
    itemType: "bag",
    ownerComment: "明日の朝食にぴったりです。",
    photoUrl: "/__mockup/images/refine-b/bakery_1.png",
    soldOut: false,
    lowStock: false,
    rating: 4.5,
  },
  {
    id: 3,
    title: "季節の彩りデリパック",
    storeName: "洋食バル キッチン太陽",
    originalPrice: 1000,
    discountedPrice: 400,
    pickupStart: "19:00",
    pickupEnd: "21:00",
    distance: "800m",
    category: "meals",
    itemType: "item",
    ownerComment: "新鮮な野菜を使ったデリです。",
    photoUrl: "/__mockup/images/refine-b/meal_2.png",
    soldOut: false,
    lowStock: false,
    rating: 4.2,
  },
  {
    id: 4,
    title: "抹茶の和菓子セット",
    storeName: "甘味処 縁",
    originalPrice: 1800,
    discountedPrice: 800,
    pickupStart: "16:00",
    pickupEnd: "18:30",
    distance: "2.1km",
    category: "bakery_sweets",
    itemType: "bag",
    ownerComment: "少し形が崩れてしまいましたが、味は絶品です。",
    photoUrl: "/__mockup/images/refine-b/bakery_2.png",
    soldOut: true,
    lowStock: false,
    rating: 4.9,
  },
  {
    id: 5,
    title: "朝どれオーガニック野菜セット",
    storeName: "ファーム直売所",
    originalPrice: 1200,
    discountedPrice: 600,
    pickupStart: "15:00",
    pickupEnd: "18:00",
    distance: "500m",
    category: "ingredients",
    itemType: "bag",
    ownerComment: "トマトとナスが多めです。",
    photoUrl: "/__mockup/images/refine-b/ingredient_1.png",
    soldOut: false,
    lowStock: true,
    rating: 4.6,
  }
];
