export const mockBags = [
  {
    id: 101,
    title: "特製ビストロボックス",
    storeName: "Bistro Lumiere",
    originalPrice: 1800,
    discountedPrice: 900,
    pickupStart: "19:00",
    pickupEnd: "20:30",
    distance: "120m",
    category: "meals",
    itemType: "bag",
    ownerComment: "本日のディナーで余ったローストビーフやパテを詰めた豪華なボックスです。ワインとご一緒に。",
    photoUrl: "/__mockup/images/refine-c/food_bento.png",
    soldOut: false,
    lowStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 102,
    title: "焼きたてパン詰め合わせ",
    storeName: "Artisan Bakery",
    originalPrice: 1200,
    discountedPrice: 500,
    pickupStart: "18:30",
    pickupEnd: "20:00",
    distance: "350m",
    category: "bakery_sweets",
    itemType: "bag",
    ownerComment: "クロワッサンやバゲットなど、本日焼き上げたパンを4〜5個お詰めします。明日の朝食にどうぞ！",
    photoUrl: "/__mockup/images/refine-c/food_bakery.png",
    soldOut: false,
    lowStock: false,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 103,
    title: "厳選おまかせ握りセット",
    storeName: "鮨 さいとう",
    originalPrice: 3000,
    discountedPrice: 1500,
    pickupStart: "21:00",
    pickupEnd: "22:00",
    distance: "800m",
    category: "meals",
    itemType: "item",
    ownerComment: "鮮度抜群のネタを握ります。キャンセルが出たため特別価格でご提供します。",
    photoUrl: "/__mockup/images/refine-c/food_sushi.png",
    soldOut: true,
    lowStock: false,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 104,
    title: "イタリアン前菜盛り合わせ",
    storeName: "Trattoria Roma",
    originalPrice: 1500,
    discountedPrice: 600,
    pickupStart: "20:00",
    pickupEnd: "21:30",
    distance: "550m",
    category: "meals",
    itemType: "bag",
    ownerComment: "カプレーゼやマリネなど、ワインに合う前菜をたっぷり詰め込みました。",
    photoUrl: "/__mockup/images/refine-c/food_italian.png",
    soldOut: false,
    lowStock: true,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: 105,
    title: "農家直送 季節の有機野菜セット",
    storeName: "Green Market",
    originalPrice: 1000,
    discountedPrice: 450,
    pickupStart: "17:00",
    pickupEnd: "19:00",
    distance: "1.2km",
    category: "ingredients",
    itemType: "bag",
    ownerComment: "少し形が不揃いですが、味は絶品の有機野菜たち。たっぷり入ってます！",
    photoUrl: "/__mockup/images/refine-c/food_ingredients.png",
    soldOut: false,
    lowStock: false,
    rating: 4.7,
    reviewCount: 45,
  },
  {
    id: 106,
    title: "パティシエ特製 ケーキの端っこ＆焼き菓子",
    storeName: "Patisserie Grandir",
    originalPrice: 1600,
    discountedPrice: 700,
    pickupStart: "19:00",
    pickupEnd: "20:30",
    distance: "400m",
    category: "bakery_sweets",
    itemType: "bag",
    ownerComment: "ケーキを作る際に出る切れ端や、少し焼きムラのあるお菓子をたっぷり。味は正規品と同じです！",
    photoUrl: "/__mockup/images/refine-c/food_cake.png",
    soldOut: false,
    lowStock: true,
    rating: 4.9,
    reviewCount: 210,
  }
];