// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo-colors/LogoVariants.tsx": () => import("../components/mockups/logo-colors/LogoVariants.tsx"),
  "./components/mockups/refine-b/BagDetail.tsx": () => import("../components/mockups/refine-b/BagDetail.tsx"),
  "./components/mockups/refine-b/Home.tsx": () => import("../components/mockups/refine-b/Home.tsx"),
  "./components/mockups/refine-b/Welcome.tsx": () => import("../components/mockups/refine-b/Welcome.tsx"),
  "./components/mockups/refine-a/BagDetail.tsx": () => import("../components/mockups/refine-a/BagDetail.tsx"),
  "./components/mockups/refine-a/Home.tsx": () => import("../components/mockups/refine-a/Home.tsx"),
  "./components/mockups/refine-a/Welcome.tsx": () => import("../components/mockups/refine-a/Welcome.tsx"),
  "./components/mockups/refine-c/BagDetail.tsx": () => import("../components/mockups/refine-c/BagDetail.tsx"),
  "./components/mockups/refine-c/Home.tsx": () => import("../components/mockups/refine-c/Home.tsx"),
  "./components/mockups/refine-c/Welcome.tsx": () => import("../components/mockups/refine-c/Welcome.tsx"),
  "./components/mockups/insta/LineBanner.tsx": () => import("../components/mockups/insta/LineBanner.tsx"),
  "./components/mockups/insta/Post1Logo.tsx": () => import("../components/mockups/insta/Post1Logo.tsx"),
  "./components/mockups/insta/Post2Takatsuki.tsx": () => import("../components/mockups/insta/Post2Takatsuki.tsx"),
  "./components/mockups/insta/Post3FoodLoss.tsx": () => import("../components/mockups/insta/Post3FoodLoss.tsx"),
  "./components/mockups/insta/Post4HowTo.tsx": () => import("../components/mockups/insta/Post4HowTo.tsx"),
  "./components/mockups/insta/Post5Story.tsx": () => import("../components/mockups/insta/Post5Story.tsx"),
  "./components/mockups/insta/Post6Store.tsx": () => import("../components/mockups/insta/Post6Store.tsx"),
  "./components/mockups/insta/Post7Benefits.tsx": () => import("../components/mockups/insta/Post7Benefits.tsx"),
  "./components/mockups/insta/Post8Area.tsx": () => import("../components/mockups/insta/Post8Area.tsx"),
  "./components/mockups/insta/Post9Download.tsx": () => import("../components/mockups/insta/Post9Download.tsx")
};
