// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/refine-a/BagDetail.tsx": () => import("../components/mockups/refine-a/BagDetail.tsx"),
  "./components/mockups/refine-a/Home.tsx": () => import("../components/mockups/refine-a/Home.tsx"),
  "./components/mockups/refine-a/Welcome.tsx": () => import("../components/mockups/refine-a/Welcome.tsx"),
  "./components/mockups/logo-colors/LogoVariants.tsx": () => import("../components/mockups/logo-colors/LogoVariants.tsx"),
  "./components/mockups/refine-c/BagDetail.tsx": () => import("../components/mockups/refine-c/BagDetail.tsx"),
  "./components/mockups/refine-c/Home.tsx": () => import("../components/mockups/refine-c/Home.tsx"),
  "./components/mockups/refine-c/Welcome.tsx": () => import("../components/mockups/refine-c/Welcome.tsx"),
  "./components/mockups/refine-b/BagDetail.tsx": () => import("../components/mockups/refine-b/BagDetail.tsx"),
  "./components/mockups/refine-b/Home.tsx": () => import("../components/mockups/refine-b/Home.tsx"),
  "./components/mockups/refine-b/Welcome.tsx": () => import("../components/mockups/refine-b/Welcome.tsx")
};
